name: DisplayMount
version: '${project.version}'
main: fr.tiltechserv.displaymount.DisplayMount
api-version: 1.19
commands:
  WARPTOOL:
    description: ceci est une comande qui donne au joueur une boussole

